package hangmanGame;

public enum Palavras {
	FRUTAS,ROUPAS,LAVANDERIA,FURADEIRA,MARTELO,BANANA,LARANJA,ZIPER,BICICLETA,ULTRAPASSAR,RAPIDO,DEVAGAR,
	CINZA,TIPOGRAFICA,JAVA,GRANDE,PEQUENO,LETRAS,PRIMITIVO,VELOCIDADE,CIDADE,GUARDA,LAR,AMOR,FELICIDADE,VERMELHO,AMARELO,PRETO,VAZIO,CHEIO,
	VALIDADE,FRESCO,SUCO,MELANCIA,ARMA,ESCOLA,UNIVERSIDADE,COMPRIMENTO
}
